Import Libraries

In [31]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, RobustScaler

Create the Dataset

In [32]:
data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}

df = pd.DataFrame(data)

df

   Gender     City    Size  Age  Fare
0    Male   Mumbai   Small   25    15
1  Female    Delhi   Large   45   300
2  Female  Chennai  Medium   32    85
3    Male   Mumbai   Large   60   450
4  Female    Delhi   Small   28    20

Task 1 — Categorical Encoding

Gender → Label Encoding

In [33]:
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

df

   Gender     City    Size  Age  Fare
0       1   Mumbai   Small   25    15
1       0    Delhi   Large   45   300
2       0  Chennai  Medium   32    85
3       1   Mumbai   Large   60   450
4       0    Delhi   Small   28    20

City → One-Hot Encoding (drop one column)

In [34]:
if 'City' in df.columns:
    df = pd.get_dummies(df, columns=['City'], drop_first=True)

Size → Ordered Label Encoding

Correct order:
Small = 0
Medium = 1
Large = 2

In [35]:
size_mapping = {
    'Small': 0,
    'Medium': 1,
    'Large': 2
}

df['Size'] = df['Size'].map(size_mapping)

# Convert City Columns to 0/1

In [36]:
df[['City_Delhi','City_Mumbai']] = df[['City_Delhi','City_Mumbai']].astype(int)

Task 2 — Feature Scaling

Because Fare contains an outlier (450), we use RobustScaler.

RobustScaler uses median and IQR, making it less sensitive to outliers.

In [37]:
scaler = RobustScaler()

df[['Age','Fare']] = scaler.fit_transform(df[['Age','Fare']])

Final DataFrame

In [38]:
df

   Gender  Size       Age      Fare  City_Delhi  City_Mumbai
0       1     0 -0.411765 -0.250000           0            1
1       0     2  0.764706  0.767857           1            0
2       0     1  0.000000  0.000000           0            0
3       1     2  1.647059  1.303571           0            1
4       0     0 -0.235294 -0.232143           1            0

# RobustScaler is used because the Fare column contains an outlier (450).
# RobustScaler scales features using the median and interquartile range (IQR),
# making it less sensitive to extreme values compared to StandardScaler or MinMaxScaler.